services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_api
    restart: always
    ports:
      - "${PORT:-3001}:3001"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_HOST=${DATABASE_HOST:-mysql}
      - DATABASE_PORT=${DATABASE_PORT:-3306}
      - DATABASE_USER=${DATABASE_USER:-root}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-root}
      - DATABASE_NAME=${DATABASE_NAME:-mydb}
    networks:
      - nest_network

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD:-root}
      - MYSQL_DATABASE=${DATABASE_NAME:-mydb}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nest_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DATABASE_PASSWORD:-root}"]
      interval: 10s
      timeout: 10s
      retries: 10

networks:
  nest_network:
    driver: bridge

volumes:
  mysql_data: